# THEME. Leave Lines 1-3 alone.
#---------------------
#remote-theme: community-archive

##############################################
# WHAT IS ALL THIS STUFF?
#---------------------
# _config is easy. Most web sites have configuration files.
# .yml means YAML. It's the data that runs your site.
# Some files, like this one, are entirely made up of YAML.
# Lines with information that isn't YAML are commented out; the lines start with #
# Those lines will be ignored by the computer but provide important information to you.
#
##############################################
# WHAT DO I DO NOW?
#---------------------
# Look for the lines that have a bunch of ### in row.
# These break _config.yml into sections.
# You'll need to do something slightly different in each section.
# If you see an instruction to "comment out", add a # to the beginning of the line(s).
# If you see an instruction to "uncomment", remove the # at the beginning of the line(s).

##############################################
# THE MOST IMPORTANT THING TO REMEMBER
#---------------------
# Variables are the things that drive your site.
# In YAML, there's a variable name--a placeholder--at the beginning of the line.
# Variables have colons after them in YAML.
# After the variable comes the actual contents of the variable, usually in double quotes
#               title: "Your Site Title"
# If you use another double quote inside your variable, it will break this config file.
#               title: "My "So-Called" Website"
#
##############################################
# START CUSTOMIZING YOUR SITE HERE
##############################################
# ABOUT YOUR SITE
#---------------------

# Title of your website
title: "Community Archive"

# Subtitle of your website. Leave blank if you want to.
subtitle: "An Archive of Our Community's Heirlooms"

# A longer description of your site (max 150 words). Helps search engines find you.
description: "Community Archive Jekyll Github Pages theme for communities with heirlooms, stories or other artifacts to save for historical purposes."

# These credits show up in the includes/_footer.html
# Main author of the website.
author: KalaniCraig
authorname : Kalani Craig
sitelogo: site_logo.jpg

# Other community social media. Leave blank if you don't have these.
email : kalani [at] kalanicraig.com
website : https://www.kalanicraig.com/
twitter : kalanicraig
github : kalanicraig
facebook : 
instagram : kalanicraig

# If you need to know how many people visit your site, go to https://analytics.google.com/
# When you finish the setup assistant, it will give you a Measurement ID: G-ABCDEFGHIJ
google_g4_analytics_id: 

##############################################
# FONTS AND COLORS
#---------------------

# Choose the FONTS you'd like to use.
# You can see these font choices in action at https://kalanicraig.com/community-archive/docs/
# Uncomment the line for the font you like. Comment out all of the other lines.

#fontchoice: quattrocento # A modern sans-serif font with classic serif accents
#fontchoice: roboto # A clean san-serif font with simple serif accents
#fontchoice: slab # A funky slab font with clean sans-serif accents
fontchoice: source # A modern serif font with clean sans-serif accents

# Choose the COLORS you'd like to use.
# You can see these color choices in action at https://kalanicraig.com/community-archive/docs/
# Uncomment the line for the color you like. Comment out all of the other lines.

#colorchoice: navy # Navy with bright teal and grey
#colorchoice: brown # Tan browns and bright greens
#colorchoice: orange # Deep browns with flame-bright orange
#colorchoice: teal # Bright teal with bright orange-yellow accents
colorchoice: dusk # Dusky purple and olive green

##############################################
# ORGANIZING YOUR COLLECTION
#---------------------
# These collections take the basic files you put together for each item in your collection and auto-group and display them.
# This takes each item in your archive collection and displays it
collections:
  items:
    output: true
    permalink: /:collection/:path:output_ext
    itemcontributor: true
    itemgroupid: true
    itemgroupname: true
    itemid: true
    itemnarrative: true
# If your collection items need to be grouped by person, family or some other group, uncomment this collection
#  groups:
#    output: true
#    permalink: /:collection/:path:output_ext
#    name: true
#    folder: true
#    sort_by: folder
# If you have oral histories that go with groups, uncomment this collection:
#  oralhistories:
#    output: true
#    permalink: /:collection/:path:output_ext
#    name: true
#    folder: true
#    sort_by: folder

##############################################
# WEBSITE ORGANIZATION
#---------------------
# MOST OF THESE THINGS DON'T NEED TO BE CHANGED.
##############################################


# This URL is the main address for absolute links. This will usually be blank.
url: ''
# If this archive will be in a folder (kalanicraig.com/community-archive/) instead of in its own main site (idahatiu.github.io) add that folder name here. This will usually be blank.
baseurl: '/community-archive'

# This URL points directly to the images directory. It needs a slash at the end.
#
# Example: <img src="{{ site.url }}{{ site.baseurl }}{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.url }}{{ site.baseurl }}{{ site.urlimg }}image.jpg)
#
urlimg: '/assets/img/'
permalink:   /:categories/:title/

year : 2022
markdown : kramdown
exclude :
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - pages/PagesOld
    - INSTALL.md
include: ['_pages']

#plugins:
#  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed
